#!/bin/sh
cd dmenu &&  make -j4 && sudo make install clean &&
cd ../dwm &&  make -j4 && sudo make install clean &&
cd ../slock && make -j4 && sudo make install clean &&
cd ../slstatus && make -j4 && sudo make install clean &&
cd ../st && make -j4 &&  sudo make install clean &&
cd ../tabbed && make -j4 && sudo make install clean
#cd ../sent && make -j4 && sudo make install clean
